image: alpine/git:latest

options:
  max-time: 15

pipelines:
  default:
    - step:
        name: Mirror to GitHub
        script:
          # 0) Garantir known_hosts do GitHub (evita prompt de fingerprint)
          - mkdir -p ~/.ssh
          - ssh-keyscan -H github.com >> ~/.ssh/known_hosts

          # 1) Estamos já no checkout do repo (feito pelo Pipelines).
          #    Precisamos garantir que temos TODAS as refs (branches/tags), não apenas shallow.
          - if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then git fetch --unshallow --tags; fi
          - git fetch --all --tags --prune

          # 2) Adicionar remoto GitHub (pode usar variável ou hardcode)
          - git remote remove github 2>/dev/null || true
          - git remote add github "${GITHUB_SSH_REPO:-git@github.com:paulobordalo/imediatus.git}"

          # 3) Push espelho (ATENÇÃO: --mirror sincroniza/apaga refs para refletir exatamente o Bitbucket)
          - git push --mirror github
